# Generated by Django 2.1rc1 on 2018-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181125_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In progress'), ('Done', 'Done')], default='Done', max_length=11),
        ),
    ]
